name: Deploy Vite+React Application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/chat-react-app:${{ github.sha }} --build-arg VITE_API_URL='${{secrets.VITE_API_URL}}' .
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/chat-react-app:${{ github.sha }}

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Pull Docker Image
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/chat-react-app:${{ github.sha }}
      - name: Remove existing container
        run: |
          if [ "$(docker ps -aq -f name=chat-react-app-container)" ]; then
            docker rm -f chat-react-app-container
          fi
      - name: Run Docker Container
        run: |
          docker run -d -p 3000:80 --name chat-react-app-container ${{ secrets.DOCKER_USERNAME }}/chat-react-app:${{ github.sha }}
